### PR TITLE
Rewrite admin view and added some new graphics, Update translations, …

### PR DESCRIPTION
**Pull request by christingruber**
Rewrite admin view and added some new graphics
Update translations
Set new module version

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @christingruber,

Here is the result on PrestaShop 1.6.1.0:
capture du 2015-07-08 10 55 56

Do you want to update the pictures to add transparency ?

**Comment by aschuler** [comment]
Hi,
yes, we should use transparency!

@christingruber They can be found in the psd-file. Please inform me if you need anything from us!

**Comment by christingruber** [comment]
Hi,

thanks for the feedback, I wrote a short email to you @aschuler.

**Comment by aschuler** [comment]
@christingruber thx for updating
@Quetzacoalt91 pictures are transparent now, thx for your hint

**Comment by Quetzacoalt91** [comment]
Hi @christingruber and @aschuler,

Thanks, your PR has just been merged and the changes will be available from tomorrow.

Best regards

**Pull request merged**
